### ISSUE TITLE
Question about ./accessory_scripts

### ISSUE THREAD

**Issue by ChenGuangji** [andrewstephenmason/obsERVer#1]
Hi, I didn't found the ./accessory_scripts directory, which include such file:
1. ./accessory_scripts/seq_formatter.py
2. ./accessory_scripts/pos_merger.py
3. ./accessory_scripts/seq_extract.py.

Could you please update the directory?
Thanks a lot for your work! @andrewstephenmason

**Comment by andrewstephenmason** [comment]
Thanks for the heads up! The directory didn't move across when I'd changed the name. There now! @ChenGuangji 
The accessory scripts mentioned are only used by S1. As S1 has some specific analyses for ALVEs, just comment out lines 34 to the end if you're doing something else.
